name: Linters

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check linters
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Lint with flake8
        uses: py-actions/flake8@v2
      - name: Check mypy
        uses: jpetrucciani/mypy-check@master
        with:
          path: "kek"
      - name: Check isort
        uses: isort/isort-action@v1
